### ISSUE TITLE
Android showing lots of spaces in bottom

### ISSUE THREAD

**Issue by harensarma** [ambistudio/react-native-spacer#10]
Thank you for this awesome library, but when on android, it is creating lots of spaces below.. see the image plz. Also plz resolve this notice if possible:

`EventEmitter.removeListener('keyboardWillHide', ...): Method has been deprecated. Please instead use `remove()` on the subscription returned by `EventEmitter.addListener`.`

![Screenshot_1639066450](https://user-images.githubusercontent.com/24252804/145433672-f9ef95b2-dd95-486a-98b8-8a40c0bb82fb.png)

**Comment by hieunc229** [comment]
Looks like Android [automatically pushes the view when focusing on the Input](https://stackoverflow.com/questions/4207880/android-how-do-i-prevent-the-soft-keyboard-from-pushing-my-view-up) (as `android:windowSoftInputMode` setting in the `AndroidManifest.xml` file)

My suggestion is don't use the Spacer when `Platform.OS === "android"`. I haven't worked with RN for a while and will need to dig a bit more about the solution, maybe disable the animation on android. 

Any suggestion?

**Comment by ddikodroid** [comment]
for android, just change `android:windowSoftInputMode` to `adjustPan`
