### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Meligy** [ambistudio/react-native-spacer#2]
Hello,
Thanks a lot for the great helper. It solves a massive problem in a very decent way.

Can you please add a license file to the repo, clarifying what people can and cannot do with the library?

Thanks again.

Cheers,

**Comment by hieunc229** [comment]
Hi @Meligy,

I am glad it helps. `react-native-spacer` is licensed under `MIT License` and I have added a `LICENSE` to the repo.

Feel free to reopen or create a new issue if you need :)

**Comment by Meligy** [comment]
Thanks heaps. That was super fast!
(and won't be assumed in the future of course!)
