### ISSUE TITLE
Not working in android

### ISSUE THREAD

**Issue by ghost** [ambistudio/react-native-spacer#9]
Not working in android also my keyBoard avoid view is not working any solution ????

**Comment by hieunc229** [comment]
Hi @chzappsinc, I haven't deal with the problem in a while. Can you create a code example on Expo Snack?

In case you haven't heard about Expo Snack, you can:
1. Visit https://snack.expo.io
2. Paste your code example
3. Click `Save` then share the link on the address bar (i.e https://snack.expo.io/xxxxx)

I can have a look and see if I can help

**Comment by ghost** [comment]
it's not working with Stack navigator hmm..

**Comment by hieunc229** [comment]
Without an example, I'd have no idea how to debug it. I'd happy to help if you put up some example
